version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `backend` directory
    directory: "/backend"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit to a maximum of 10 pull requests at once
    open-pull-requests-limit: 10
    # Add assignees
    assignees:
      - "mrudul-UmassD"
    # Labels on pull requests for security and dependency updates
    labels:
      - "dependencies"
      - "npm"
      
  # Enable version updates for npm in frontend
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `frontend` directory
    directory: "/frontend"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit to a maximum of 10 pull requests at once
    open-pull-requests-limit: 10
    # Add assignees
    assignees:
      - "mrudul-UmassD"
    # Labels on pull requests for security and dependency updates
    labels:
      - "dependencies"
      - "npm"
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "mrudul-UmassD"
    labels:
      - "dependencies"
      - "github-actions" 