services:
  - type: web
    name: smart-sprint
    runtime: node
    buildCommand: npm run install-all && cd frontend && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://smart-sprint.onrender.com
      - key: PORT
        value: 10000
    autoDeploy: true 